### ISSUE TITLE
Error: LIBUSB_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by arezd** [node-usb/node-usb#191]
HI 

THANK YOU FOR YOUR SOLUTION. TRIED IT WITH THIS CODE ON MAC OSX

var usb = require("usb")

// Mouse has idProduct = 50484
// Mouse has idVendor = 1133
pid = 50484
vid = 1133
interfaceNum = 1
endPointAdress = 130
lengthTransfer = 1

var devices = usb.getDeviceList();
//console.log (devices.length)

// Selection the right device

/*for (i = 0  ; i < devices.length; i++){
  console.log(devices[i].deviceDescriptor.idProduct)
  console.log(devices[i].deviceDescriptor.idVendor)
}*/

mouseDevice = usb.findByIds(vid, pid)
//console.log(mouseDevice.configDescriptor.bNumInterfaces)
mouseDevice.open()

interface = mouseDevice.interface(interfaceNum)
console.log(interface.endpoints)
interface.claim()
interface.endpoint(endPointAdress).startPoll(3,64)
//interface.endpoint(endPointAdress).stopPoll(100)
//interface.endpoint(endPointAdress).transfer(lengthTransfer, function(error,data){

//})

console.log(interface)
//interface.release()
//mouseDevice.close()

AND I GET THIS ERROR :

node reader.js 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_ERROR_NOT_FOUND
    at Error (native)
    at startTransfer (/Users/arezkidji/Desktop/MiSenseApp/js/node_modules/usb/usb.js:333:6)
    at Array.forEach (native)
    at InEndpoint.startPoll (/Users/arezkidji/Desktop/MiSenseApp/js/node_modules/usb/usb.js:340:21)
    at Object.<anonymous> (/Users/arezkidji/Desktop/MiSenseApp/js/reader.js:28:36)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by btxtiger** [comment]
I'm having the same issue, maybe this is a workaround
https://github.com/tessel/node-usb/issues/61
I'll try it tomorrow

**Comment by thegecko** [comment]
Closing this issue due to inactivity, please create a new issue as required.
