### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by 954053260** [node-usb/node-usb#314]
I get the following error after installing the usb package and calling require('usb'). My environment is Windows 7 32 bit
C:\Users\cvter\Desktop\work\node-test\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?\C:\Users\cvter\Desktop\work\node-test\node_modules\usb\build\Release\usb_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (C:\Users\cvter\Desktop\work\node-test\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\cvter\Desktop\work\node-test\node_modules\usb\usb.js:1:119)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Comment by thegecko** [comment]
Closing due to inactivity, please reopen this issue if it persists with the latest release.
