### ISSUE TITLE
Crash WinUSB when disconnecting the device

### ISSUE THREAD

**Issue by LorenzGardner** [node-usb/node-usb#59]
Error: LIBUSB_ERROR_NO_DEVICE
    at InEndpoint.Endpoint.stopStream (C:\dev\B4win\node_modules\usb\usb.js:243:
27)
    at Transfer.transferDone (C:\dev\B4win\node_modules\usb\usb.js:276:9)

If you pull out the USB device LIBUSB_ERROR_NO_DEVICE is thrown when attempting to stop the stream. On linux this all works without issue, so I'm guessing a difference in the way winUSB works? 

node usb should probably handle errors from the stop stream event. Or perhaps not bother trying to close the stream in an error handler?

**Comment by jaller94** [comment]
I got a similar error on Manjaro Linux when unplugging a USB device.

`usb` from NPM: 1.6.2 
`libusb` from the Arch repo: 1.0.23-2
```
/opt/project/node_modules/usb/usb.js:330
	return this.device.__attachKernelDriver(this.id)
	                   ^

Error: LIBUSB_ERROR_NO_DEVICE
    at Interface.attachKernelDriver (/opt/project/node_modules/usb/usb.js:330:21)
    at InEndpoint.<anonymous> (/opt/project/co2_monitor.js:83:33)
    at Object.onceWrapper (events.js:411:28)
    at InEndpoint.emit (events.js:317:22)
    at Transfer.transferDone (/opt/project/node_modules/usb/usb.js:454:10) {
  errno: -4
}
```

**Comment by thegecko** [comment]
Closing this issue due to inactivity, please create a new issue as required.
