### ISSUE TITLE
node-gyp failed to build 

### ISSUE THREAD

**Issue by dingshaohua-com** [node-usb/node-usb#819]
build err in macos15

```shell
> electron-builder

  • electron-builder  version=25.0.5 os=24.0.0
  • loaded configuration  file=/my-app/apps/app/electron-builder.json
  • description is missed in the package.json  appPackageFile=/my-app/apps/app/package.json
  • author is missed in the package.json  appPackageFile=/my-app/apps/app/package.json
  • writing effective config  file=/my-app/dist/builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=31.6.0 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=usb arch=x64
  ⨯ Traceback (most recent call last):
  File "/my-app/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/my-app/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/my-app/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (/my-app/node_modules/.pnpm/node-gyp@9.4.1/node_modules/node-gyp/lib/configure.js:325:16)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)


  ⨯ node-gyp failed to rebuild '/my-app/node_modules/.pnpm/usb@2.14.0/node_modules/usb'  failedTask=build stackTrace=Error: node-gyp failed to rebuild '/my-app/node_modules/.pnpm/usb@2.14.0/node_modules/usb'
    at ChildProcess.<anonymous> (/my-app/node_modules/.pnpm/@electron+rebuild@3.6.0/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
`

**Comment by thegecko** [comment]
https://github.com/node-usb/node-usb?tab=readme-ov-file#electron
